#!/usr/bin/env node

var _ = require('dry-underscore');

if(process.argv[2] === "install"){
    _.shell("rm -rf ./copy && cp -r . ./copy && cd copy && dry-test-vm ./tests/install.sh --export . && cd ..");
}else{
    _.shell("dry-test-vm ./tests/scripts/echo.sh --export ./tests/scripts");
}
    
